version: '3'
services:
  db:
    container_name: postgres
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks:
      - private-network
  cache:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"
    networks:
      - private-network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  redis-cache-service:
    image: 'redis-cache-service'
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    links:
      - cache
      - db
    depends_on:
      - cache
      - db
    ports:
      - "8011-8013:8080"
    networks:
      - private-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_REDIS_HOST: cache
      SPRING_REDIS_PORT: 6379
networks:
  private-network:
    driver: bridge