spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    cache-names: numbers
    redis:
      time-to-live: 60000
      cache-null-values: false
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

logging.level:
  org.springframework.data.redis: TRACE
  redis.clients: TRACE